<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('customers')->delete();

        DB::table('customers')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'ALEX GOMEZ',
                'identification' => '91520221',
                'dv' => 0,
                'address' => 'BARRIO CAMPO MADRID TORRE 2 APTO 2012',
                'phone' => '3168521677',
                'email' => 'alexgomez@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 0,
                'used' => 0,
                'available' => 0,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'JAIRO SUAREZ',
                'identification' => '91343991',
                'dv' => 7,
                'address' => 'NN',
                'phone' => '3014109204',
                'email' => 'diseno.web.sder@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 500000,
                'used' => 0,
                'available' => 500000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'MAPRES',
                'identification' => '2222',
                'dv' => 0,
                'address' => 'CALLE 31#7-86 BUCARAMANGA',
                'phone' => '3158666391',
                'email' => 'mapres.sas@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 1000000,
                'used' => 0,
                'available' => 1000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 6,
                'liability_id' => 117,
                'organization_id' => 1,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'VENTAS GENERALES',
                'identification' => '9999',
                'dv' => 0,
                'address' => 'NN',
                'phone' => '3188868145',
                'email' => 'lorenzomontalvo1986@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 500000,
                'used' => 0,
                'available' => 500000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'UBALDO GARCIA',
                'identification' => '13815903',
                'dv' => 1,
                'address' => 'NN',
                'phone' => '3223572355',
                'email' => 'joseubaldogarcia393@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 5000000,
                'used' => 0,
                'available' => 500000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'CRISTIAN TUA',
                'identification' => '7895',
                'dv' => 0,
                'address' => 'BAVARIA II',
                'phone' => '8563214',
                'email' => 'critiian@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 500000,
                'used' => 0,
                'available' => 500000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'INDUNORTE SAS',
                'identification' => '93478',
                'dv' => 0,
                'address' => 'hgigsuguig',
                'phone' => '464646',
                'email' => 'indunorte@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 2000000,
                'used' => 0,
                'available' => 2000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 6,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'CARLOS ARANGO',
                'identification' => '91526687',
                'dv' => 0,
                'address' => 'CHATARRERIA DELICIAS ALTAS',
                'phone' => '3167273282',
                'email' => 'carlosmontes9000@hotmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 8000000,
                'used' => 0,
                'available' => 8000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'NORBERTO GOMEZ',
                'identification' => '10167775',
                'dv' => 0,
                'address' => 'SAN FRANCISCO CALLE 91-24',
                'phone' => '3012412995',
                'email' => 'norbertogomez@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 50000000,
                'used' => 0,
                'available' => 50000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'NEYDER VARGAS',
                'identification' => '1098735312',
                'dv' => 5,
                'address' => 'CL 69 7B 01 BRR JUAN XXIII',
                'phone' => '3112456787',
                'email' => 'metalkeyornamentacion@hotmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 500000,
                'used' => 0,
                'available' => 500000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'LUIS NEIRA',
                'identification' => '9692444',
                'dv' => 8,
                'address' => 'URB CAMPO MADRID TORRE 35 APTO 5205',
                'phone' => '3183094240',
                'email' => 'luisneira@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 1000000,
                'used' => 0,
                'available' => 1000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'YENNER SANDOVAL',
                'identification' => '1050542682',
                'dv' => 0,
                'address' => 'RIO DE ORO SECTOR 3 CASA 143',
                'phone' => '3105089247',
                'email' => 'yennersandoval@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 1000000,
                'used' => 0,
                'available' => 1000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'SANIEL TORRES',
                'identification' => '1065904241',
                'dv' => 0,
                'address' => 'BAVARIA II CASA 143',
                'phone' => '3238899112',
                'email' => 'torressaniel7@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 1000000,
                'used' => 0,
                'available' => 1000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'SINDY CASTRO',
                'identification' => '1140844802',
                'dv' => 0,
                'address' => 'CRR 12 CLL 85-21 SOLEDAD ATLANTICO',
                'phone' => '3008077597',
                'email' => 'castroprietosindypaola@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 1000000,
                'used' => 0,
                'available' => 1000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'HAROLD REY',
                'identification' => '91238972',
                'dv' => 0,
                'address' => 'BAVARIA II CASA 10',
                'phone' => '3107764768',
                'email' => 'haroldr415@hotmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 1000000,
                'used' => 0,
                'available' => 1000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'FRANCELINA PINZON',
                'identification' => '57290886',
                'dv' => 0,
                'address' => 'SAN ALBERTO CESAR VIA EL MAR',
                'phone' => '3006713374',
                'email' => 'francelinapinzon@gmail.com',
                'merchant_registration' => '0.00',
                'credit_limit' => 50000000,
                'used' => 0,
                'available' => 50000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'INGENIERIA P&C S.A.S.',
                'identification' => '901754008',
                'dv' => 2,
                'address' => 'CALL 41  16-52 PISO 2',
                'phone' => '3172213878',
                'email' => 'LISE.TATIANA16@GMAIL.COM',
                'merchant_registration' => '0.00',
                'credit_limit' => 1000000,
                'used' => 0,
                'available' => 1000000,
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 881,
                'identification_type_id' => 6,
                'liability_id' => 117,
                'organization_id' => 1,
                'regime_id' => 2,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'INVERSIONES MONTERREY KG S.A.S.',
                'identification' => '901738686',
                'dv' => 9,
                'address' => 'R 43A 18 SUR 135 OF 912',
                'phone' => '3106417656',
                'email' => 'INVERSIONESMONTERREYKG@GMAIL.COM',
                'merchant_registration' => '0.00',
                'credit_limit' => 2000000,
                'used' => 0,
                'available' => 2000000,
                'status' => 'active',
                'department_id' => 1,
                'municipality_id' => 19,
                'identification_type_id' => 6,
                'liability_id' => 117,
                'organization_id' => 1,
                'regime_id' => 1,
                'created_at' => '2024-07-23 12:00:00',
                'updated_at' => '2024-07-23 12:00:00'
            ),

        ));
    }
}

