<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->delete();

        DB::table('products')->insert(array (
            0 =>
            array (
                'id' => 1,
                'code' => 1,
                'name' => 'CHATARRA',
                'price' => 900,
                'sale_price' => 900,
                'stock' => '6231.55',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 1,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            1 =>
            array (
                'id' => 2,
                'code' => 2,
                'name' => 'COBRE',
                'price' => 29000,
                'sale_price' => 0,
                'stock' => '107.90',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 2,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            2 =>
            array (
                'id' => 3,
                'code' => 3,
                'name' => 'BRONCE',
                'price' => 19000,
                'sale_price' => 19000,
                'stock' => '94.10',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 2,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            3 =>
            array (
                'id' => 4,
                'code' => 4,
                'name' => 'RADIADOR DE ALUMINIO',
                'price' => 3700,
                'sale_price' => 0,
                'stock' => '81.60',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 3,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            4 =>
            array (
                'id' => 5,
                'code' => 5,
                'name' => 'RADIADOR DE BRONCE',
                'price' => 19000,
                'sale_price' => 0,
                'stock' => '45.20',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 3,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            5 =>
            array (
                'id' => 6,
                'code' => 6,
                'name' => 'RADIADOR MIXTO-COBRE',
                'price' => 13500,
                'sale_price' => 0,
                'stock' => '48.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 3,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            6 =>
            array (
                'id' => 7,
                'code' => 7,
                'name' => 'ALUMINIO',
                'price' => 5800,
                'sale_price' => 5800,
                'stock' => '1104.40',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            7 =>
            array (
                'id' => 8,
                'code' => 8,
                'name' => 'POTE',
                'price' => 5800,
                'sale_price' => 5800,
                'stock' => '1022.90',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            8 =>
            array (
                'id' => 9,
                'code' => 9,
                'name' => 'PERFIL',
                'price' => 6500,
                'sale_price' => 0,
                'stock' => '1309.10',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            9 =>
            array (
                'id' => 10,
                'code' => 10,
                'name' => 'GUAYA DE ALUMINIO',
                'price' => 7000,
                'sale_price' => 12000,
                'stock' => '200.30',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            10 =>
            array (
                'id' => 11,
                'code' => 11,
                'name' => 'ANTIMONIO',
                'price' => 5000,
                'sale_price' => 6000,
                'stock' => '13.70',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            11 =>
            array (
                'id' => 12,
                'code' => 12,
                'name' => 'PLANCHA',
                'price' => 2500,
                'sale_price' => 0,
                'stock' => '16.90',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            12 =>
            array (
                'id' => 13,
                'code' => 13,
                'name' => 'BANDA',
                'price' => 3000,
                'sale_price' => 3000,
                'stock' => '505.40',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            13 =>
            array (
                'id' => 14,
                'code' => 14,
                'name' => 'CILINDRO DE MOTO',
                'price' => 2500,
                'sale_price' => 0,
                'stock' => '1239.90',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            14 =>
            array (
                'id' => 15,
                'code' => 15,
                'name' => 'PLOMO',
                'price' => 6000,
                'sale_price' => 0,
                'stock' => '71.50',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 5,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            15 =>
            array (
                'id' => 16,
                'code' => 16,
                'name' => 'BALANCIN',
                'price' => 3000,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 5,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            16 =>
            array (
                'id' => 17,
                'code' => 17,
                'name' => 'VIRUTA DE ALUMINIO',
                'price' => 600,
                'sale_price' => 0,
                'stock' => '123.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 6,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            17 =>
            array (
                'id' => 18,
                'code' => 18,
                'name' => 'COLADO-GRIS',
                'price' => 1400,
                'sale_price' => 1400,
                'stock' => '1106.60',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 7,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            18 =>
            array (
                'id' => 19,
                'code' => 19,
                'name' => 'UNIDAD',
                'price' => 28000,
                'sale_price' => 0,
                'stock' => '508.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 8,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            19 =>
            array (
                'id' => 20,
                'code' => 20,
                'name' => 'COCO',
                'price' => 17000,
                'sale_price' => 0,
                'stock' => '113.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 8,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            20 =>
            array (
                'id' => 21,
                'code' => 21,
                'name' => 'ACERO',
                'price' => 3800,
                'sale_price' => 3500,
                'stock' => '4154.60',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 9,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            21 =>
            array (
                'id' => 22,
                'code' => 22,
                'name' => 'BATERIA N40',
                'price' => 26500,
                'sale_price' => 0,
                'stock' => '2.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            22 =>
            array (
                'id' => 23,
                'code' => 23,
                'name' => 'BATERIA N42',
                'price' => 32500,
                'sale_price' => 0,
                'stock' => '1.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            23 =>
            array (
                'id' => 24,
                'code' => 24,
                'name' => 'BATERIA N48',
                'price' => 38500,
                'sale_price' => 0,
                'stock' => '2.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            24 =>
            array (
                'id' => 25,
                'code' => 25,
                'name' => 'BATERIA N27',
                'price' => 44500,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            25 =>
            array (
                'id' => 26,
                'code' => 26,
                'name' => 'BATERIA 30H',
                'price' => 57500,
                'sale_price' => 0,
                'stock' => '1.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            26 =>
            array (
                'id' => 27,
                'code' => 27,
                'name' => 'BATERIA 4D',
                'price' => 84500,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            27 =>
            array (
                'id' => 28,
                'code' => 28,
                'name' => 'BATERIA 8D',
                'price' => 100000,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            28 =>
            array (
                'id' => 29,
                'code' => 29,
                'name' => 'BATERIA MOTO-TIERRA',
                'price' => 2600,
                'sale_price' => 0,
                'stock' => '45.60',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            29 =>
            array (
                'id' => 30,
                'code' => 30,
                'name' => 'ESTACIONARIA',
                'price' => 3000,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            30 =>
            array (
                'id' => 31,
                'code' => 31,
                'name' => 'PASTA',
                'price' => 900,
                'sale_price' => 900,
                'stock' => '1017.80',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            31 =>
            array (
                'id' => 32,
                'code' => 32,
                'name' => 'CAJA VACIA',
                'price' => 4000,
                'sale_price' => 0,
                'stock' => '342.25',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            32 =>
            array (
                'id' => 33,
                'code' => 33,
                'name' => 'CAJA LLENA',
                'price' => 5000,
                'sale_price' => 4800,
                'stock' => '464.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            33 =>
            array (
                'id' => 34,
                'code' => 34,
                'name' => 'RIN DE MOTO',
                'price' => 6000,
                'sale_price' => 0,
                'stock' => '19.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 12,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            34 =>
            array (
                'id' => 35,
                'code' => 35,
                'name' => 'RIN PEQUEÑO',
                'price' => 2000,
                'sale_price' => 0,
                'stock' => '130.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 12,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            35 =>
            array (
                'id' => 36,
                'code' => 36,
                'name' => 'RIN GRANDE',
                'price' => 2500,
                'sale_price' => 0,
                'stock' => '236.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 12,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            36 =>
            array (
                'id' => 37,
                'code' => 37,
                'name' => 'CELULAR',
                'price' => 22000,
                'sale_price' => 0,
                'stock' => '131.90',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            37 =>
            array (
                'id' => 38,
                'code' => 38,
                'name' => 'TARJETA C.P',
                'price' => 13000,
                'sale_price' => 0,
                'stock' => '3.30',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            38 =>
            array (
                'id' => 39,
                'code' => 39,
                'name' => 'TARJETA TIPO3',
                'price' => 5000,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            39 =>
            array (
                'id' => 40,
                'code' => 40,
                'name' => 'PORTATIL',
                'price' => 4000,
                'sale_price' => 0,
                'stock' => '38.50',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            40 =>
            array (
                'id' => 41,
                'code' => 41,
                'name' => 'TABLET',
                'price' => 4000,
                'sale_price' => 0,
                'stock' => '6.30',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            41 =>
            array (
                'id' => 42,
                'code' => 42,
                'name' => 'RADIOGRAFIA',
                'price' => 4000,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            42 =>
            array (
                'id' => 43,
                'code' => 43,
                'name' => 'BAJOGRADO',
                'price' => 1500,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            43 =>
            array (
                'id' => 44,
                'code' => 44,
                'name' => 'ARCHIVO',
                'price' => 800,
                'sale_price' => 800,
                'stock' => '5712.80',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 14,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            44 =>
            array (
                'id' => 45,
                'code' => 45,
                'name' => 'CARTON',
                'price' => 500,
                'sale_price' => 400,
                'stock' => '959.70',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 14,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            45 =>
            array (
                'id' => 46,
                'code' => 46,
                'name' => 'PLIEGA',
                'price' => 200,
                'sale_price' => 0,
                'stock' => '34.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 14,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            46 =>
            array (
                'id' => 47,
                'code' => 47,
                'name' => 'PVC',
                'price' => 500,
                'sale_price' => 500,
                'stock' => '1236.05',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            47 =>
            array (
                'id' => 48,
                'code' => 48,
                'name' => 'BOTA',
                'price' => 400,
                'sale_price' => 0,
                'stock' => '3548.94',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 14,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            48 =>
            array (
                'id' => 49,
                'code' => 49,
                'name' => 'FILTROS',
                'price' => 600,
                'sale_price' => 0,
                'stock' => '7404.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 1,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            49 =>
            array (
                'id' => 50,
                'code' => 50,
                'name' => 'REVUELTO',
                'price' => 900,
                'sale_price' => 500,
                'stock' => '7926.80',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            50 =>
            array (
                'id' => 51,
                'code' => 51,
                'name' => 'PET',
                'price' => 800,
                'sale_price' => 0,
                'stock' => '2523.32',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            51 =>
            array (
                'id' => 52,
                'code' => 52,
                'name' => 'MATERIAL',
                'price' => 1600,
                'sale_price' => 3000,
                'stock' => '1410.90',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 16,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            52 =>
            array (
                'id' => 53,
                'code' => 53,
                'name' => 'MALAS',
                'price' => 800,
                'sale_price' => 2700,
                'stock' => '615.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 2,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            53 =>
            array (
                'id' => 54,
                'code' => 54,
                'name' => 'COLOR',
                'price' => 200,
                'sale_price' => 200,
                'stock' => '50.50',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 640,
                'created_at' => null,
                'updated_at' => null
            ),
            54 =>
            array (
                'id' => 55,
                'code' => 55,
                'name' => 'BARBACHA',
                'price' => 1000,
                'sale_price' => 0,
                'stock' => '460.40',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 16,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            55 =>
            array (
                'id' => 56,
                'code' => 56,
                'name' => 'PRODUCTO PR',
                'price' => 0,
                'sale_price' => 1000,
                'stock' => '229.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 17,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            56 =>
            array (
                'id' => 57,
                'code' => 57,
                'name' => 'TELEVISOR',
                'price' => 1000,
                'sale_price' => 1000,
                'stock' => '428.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            57 =>
            array (
                'id' => 58,
                'code' => 58,
                'name' => 'RADIADOR DE BRONCE',
                'price' => 16000,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 3,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            58 =>
            array (
                'id' => 59,
                'code' => 59,
                'name' => 'MOTOR DE LAVADORA',
                'price' => 10000,
                'sale_price' => 30000,
                'stock' => '42.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 16,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            59 =>
            array (
                'id' => 60,
                'code' => 60,
                'name' => 'BUENAS',
                'price' => 2000,
                'sale_price' => 2700,
                'stock' => '147.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 2,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            60 =>
            array (
                'id' => 61,
                'code' => 61,
                'name' => 'SOLDADURA',
                'price' => 0,
                'sale_price' => 85000,
                'stock' => '4.50',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            61 =>
            array (
                'id' => 62,
                'code' => 62,
                'name' => 'DISCO DE CORTE',
                'price' => 0,
                'sale_price' => 7000,
                'stock' => '9.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            62 =>
            array (
                'id' => 63,
                'code' => 63,
                'name' => 'LAMINAS DE ZINC',
                'price' => 10000,
                'sale_price' => 23000,
                'stock' => '90.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            63 =>
            array (
                'id' => 64,
                'code' => 64,
                'name' => 'PET MOJADO',
                'price' => 200,
                'sale_price' => 200,
                'stock' => '412.55',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            64 =>
            array (
                'id' => 65,
                'code' => 65,
                'name' => 'TAPAS',
                'price' => 800,
                'sale_price' => 0,
                'stock' => '154.50',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            65 =>
            array (
                'id' => 66,
                'code' => 66,
                'name' => 'PLASTICO',
                'price' => 800,
                'sale_price' => 600,
                'stock' => '2232.14',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 14,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            66 =>
            array (
                'id' => 67,
                'code' => 67,
                'name' => 'BANDA',
                'price' => 3000,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            67 =>
            array (
                'id' => 68,
                'code' => 68,
                'name' => 'ANGULO',
                'price' => 2000,
                'sale_price' => 3000,
                'stock' => '1063.60',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 16,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            68 =>
            array (
                'id' => 69,
                'code' => 69,
                'name' => 'CABLE',
                'price' => 6000,
                'sale_price' => 0,
                'stock' => '143.60',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 2,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            69 =>
            array (
                'id' => 70,
                'code' => 70,
                'name' => 'MANGUERA',
                'price' => 700,
                'sale_price' => 0,
                'stock' => '821.80',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            70 =>
            array (
                'id' => 71,
                'code' => 71,
                'name' => 'SOPLADO',
                'price' => 800,
                'sale_price' => 600,
                'stock' => '199.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            71 =>
            array (
                'id' => 72,
                'code' => 72,
                'name' => 'ESTRIBAS',
                'price' => 800,
                'sale_price' => 32000,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            72 =>
            array (
                'id' => 73,
                'code' => 73,
                'name' => 'VIDRIO DE SOLDAR',
                'price' => 0,
                'sale_price' => 3000,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            73 =>
            array (
                'id' => 74,
                'code' => 74,
                'name' => 'CADENA',
                'price' => 1000,
                'sale_price' => 0,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 16,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            74 =>
            array (
                'id' => 75,
                'code' => 75,
                'name' => 'CANECA',
                'price' => 20000,
                'sale_price' => 0,
                'stock' => '37.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 1,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            75 =>
            array (
                'id' => 76,
                'code' => 76,
                'name' => 'TERMOSTATO',
                'price' => 2000,
                'sale_price' => 0,
                'stock' => '30.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 2,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            76 =>
            array (
                'id' => 77,
                'code' => 77,
                'name' => 'GUANTES',
                'price' => 0,
                'sale_price' => 9000,
                'stock' => '40.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            77 =>
            array (
                'id' => 78,
                'code' => 78,
                'name' => 'SACAS GRANDES',
                'price' => 8000,
                'sale_price' => 0,
                'stock' => '995.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            78 =>
            array (
                'id' => 79,
                'code' => 79,
                'name' => 'CD',
                'price' => 1000,
                'sale_price' => 1500,
                'stock' => '69.90',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            79 =>
            array (
                'id' => 80,
                'code' => 80,
                'name' => 'CPU',
                'price' => 15000,
                'sale_price' => 50000,
                'stock' => '31.10',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            80 =>
            array (
                'id' => 81,
                'code' => 81,
                'name' => 'TARJETA BAJO GRADO',
                'price' => 1500,
                'sale_price' => 0,
                'stock' => '5.70',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            81 =>
            array (
                'id' => 82,
                'code' => 82,
                'name' => 'PROCESADORES',
                'price' => 2000,
                'sale_price' => 0,
                'stock' => '6.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            82 =>
            array (
                'id' => 83,
                'code' => 83,
                'name' => 'EJE',
                'price' => 2000,
                'sale_price' => 3000,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 16,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            83 =>
            array (
                'id' => 84,
                'code' => 84,
                'name' => 'BALA',
                'price' => 30000,
                'sale_price' => 50000,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 8,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            84 =>
            array (
                'id' => 85,
                'code' => 85,
                'name' => 'LADRILLOS',
                'price' => 1300,
                'sale_price' => 0,
                'stock' => '600.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 16,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            85 =>
            array (
                'id' => 86,
                'code' => 86,
                'name' => 'TUBO METALICO DE SEGUNDA',
                'price' => 3500,
                'sale_price' => 0,
                'stock' => '1937.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 16,
                'measure_unit_id' => 40,
                'created_at' => null,
                'updated_at' => null
            ),
            86 =>
            array (
                'id' => 87,
                'code' => 87,
                'name' => 'FUENTE',
                'price' => 1500,
                'sale_price' => 0,
                'stock' => '9.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 13,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            87 =>
            array (
                'id' => 88,
                'code' => 88,
                'name' => 'PLATINA DE ACERO',
                'price' => 3000,
                'sale_price' => 10000,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 9,
                'measure_unit_id' => 44,
                'created_at' => null,
                'updated_at' => null
            ),
            88 =>
            array (
                'id' => 89,
                'code' => 89,
                'name' => 'PINTURA',
                'price' => 0,
                'sale_price' => 45000,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            89 =>
            array (
                'id' => 90,
                'code' => 90,
                'name' => 'DELANTAL',
                'price' => 10000,
                'sale_price' => 20000,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            90 =>
            array (
                'id' => 91,
                'code' => 91,
                'name' => 'GUANTE SOLD',
                'price' => 10000,
                'sale_price' => 20000,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            91 =>
            array (
                'id' => 92,
                'code' => 92,
                'name' => 'TINER',
                'price' => 18000,
                'sale_price' => 18000,
                'stock' => '18.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            92 =>
            array (
                'id' => 93,
                'code' => 93,
                'name' => 'PLATINA 1"x 1°',
                'price' => 16000,
                'sale_price' => 16000,
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 1,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            93 =>
            array (
            'id' => 94,
            'code' => 94,
            'name' => 'TUBO 2x1°',
            'price' => 22000,
            'sale_price' => 22000,
            'stock' => '0.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 18,
            'measure_unit_id' => 70,
            'created_at' => null,
            'updated_at' => null
        ),
            94 =>
            array (
            'id' => 95,
            'code' => 95,
            'name' => 'MOTOR',
            'price' => 2500,
            'sale_price' => 10000,
            'stock' => '126.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 2,
            'measure_unit_id' => 70,
            'created_at' => null,
            'updated_at' => null
        ),
            95 =>
            array (
            'id' => 96,
            'code' => 96,
            'name' => 'SALDO ANTERIOR',
            'price' => 1000,
            'sale_price' => 2000,
            'stock' => '0.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 18,
            'measure_unit_id' => 70,
            'created_at' => null,
            'updated_at' => null
        ),
            96 =>
            array (
            'id' => 97,
            'code' => 97,
            'name' => 'LIMPIEZA',
            'price' => 3500,
            'sale_price' => 5000,
            'stock' => '263.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 2,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            97 =>
            array (
            'id' => 98,
            'code' => 98,
            'name' => 'MALLA',
            'price' => 1600,
            'sale_price' => 2500,
            'stock' => '0.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 16,
            'measure_unit_id' => 40,
            'created_at' => null,
            'updated_at' => null
        ),
            98 =>
            array (
            'id' => 99,
            'code' => 99,
            'name' => 'VIRUTA DE BRONCE',
            'price' => 10000,
            'sale_price' => 0,
            'stock' => '0.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 2,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            99 =>
            array (
            'id' => 100,
            'code' => 100,
            'name' => 'COBRE BRILLANTE',
            'price' => 26000,
            'sale_price' => 0,
            'stock' => '0.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 2,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            100 =>
            array (
            'id' => 101,
            'code' => 101,
            'name' => 'VIDRIO',
            'price' => 50,
            'sale_price' => 50,
            'stock' => '164.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 14,
            'measure_unit_id' => 640,
            'created_at' => null,
            'updated_at' => null
        ),
            101 =>
            array (
            'id' => 102,
            'code' => 102,
            'name' => 'TARJETAS CUADRO GRANDE',
            'price' => 32000,
            'sale_price' => 15000,
            'stock' => '0.80',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 14,
            'measure_unit_id' => 640,
            'created_at' => null,
            'updated_at' => null
        ),
            102 =>
            array (
            'id' => 103,
            'code' => 103,
            'name' => 'TARJETA CUADRO PEQUEÑO',
            'price' => 12000,
            'sale_price' => 10000,
            'stock' => '2.30',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 14,
            'measure_unit_id' => 640,
            'created_at' => null,
            'updated_at' => null
        ),
            103 =>
            array (
            'id' => 104,
            'code' => 104,
            'name' => 'GUAYA ENCAUCHETADA',
            'price' => 3000,
            'sale_price' => 2000,
            'stock' => '42.50',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 4,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            104 =>
            array (
            'id' => 105,
            'code' => 105,
            'name' => 'POLISOMBRA 80X100',
            'price' => 400000,
            'sale_price' => 400000,
            'stock' => '0.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 18,
            'measure_unit_id' => 70,
            'created_at' => null,
            'updated_at' => null
        ),
            105 =>
            array (
            'id' => 106,
            'code' => 106,
            'name' => 'SACAS MEDIANAS',
            'price' => 200,
            'sale_price' => 200,
            'stock' => '200.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 16,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            106 =>
            array (
            'id' => 107,
            'code' => 107,
            'name' => 'ALAMBRE',
            'price' => 3000,
            'sale_price' => 3000,
            'stock' => '92.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 18,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            107 =>
            array (
            'id' => 108,
            'code' => 108,
            'name' => 'LAMINAS ZIN 1*20',
            'price' => 35000,
            'sale_price' => 35000,
            'stock' => '0.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 18,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            108 =>
            array (
            'id' => 109,
            'code' => 109,
            'name' => 'TUBO 3X1 MEDIA',
            'price' => 76000,
            'sale_price' => 76000,
            'stock' => '0.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 18,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            109 =>
            array (
            'id' => 110,
            'code' => 110,
            'name' => 'CAJA SOLDADURA',
            'price' => 280000,
            'sale_price' => 280000,
            'stock' => '0.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 18,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            110 =>
            array (
            'id' => 111,
            'code' => 111,
            'name' => 'CAJA NEGRA',
            'price' => 3000,
            'sale_price' => 3000,
            'stock' => '5.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 11,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            111 =>
            array (
            'id' => 112,
            'code' => 112,
            'name' => 'VARILLA',
            'price' => 25000,
            'sale_price' => 25000,
            'stock' => '57.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'product',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 18,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),
            112 =>
            array (
            'id' => 113,
            'code' => 113,
            'name' => 'DIA TRABAJO',
            'price' => 150000,
            'sale_price' => 150000,
            'stock' => '0.00',
            'commission' => 0,
            'stock_min' => 1,
            'type_product' => 'service',
            'status' => 'active',
            'imageName' => null,
            'image' => null,
            'category_id' => 16,
            'measure_unit_id' => 44,
            'created_at' => null,
            'updated_at' => null
        ),

        ));
    }
}
