<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->delete();

        DB::table('products')->insert(array (
            0 =>
            array (
                'id' => 1,
                'code' => 'P001',
                'name' => 'COBRE 1B',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 11,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            1 =>
            array (
                'id' => 2,
                'code' => 'P002',
                'name' => 'COBRE MIXTO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 11,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            2 =>
            array (
                'id' => 3,
                'code' => 'P003',
                'name' => 'CABLE DE COBRE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 11,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            3 =>
            array (
                'id' => 4,
                'code' => 'P004',
                'name' => 'RADIADOR DE COBRE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 12,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            4 =>
            array (
                'id' => 5,
                'code' => 'P005',
                'name' => 'RADIADOR MIXTO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 12,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            5 =>
            array (
                'id' => 6,
                'code' => 'P006',
                'name' => 'RADIADOR ALUMINIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 12,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            6 =>
            array (
                'id' => 7,
                'code' => 'P007',
                'name' => 'ALUMINIO GRUESO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            7 =>
            array (
                'id' => 8,
                'code' => 'P008',
                'name' => 'ALUMINIO BLANDO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            8 =>
            array (
                'id' => 9,
                'code' => 'P009',
                'name' => 'ALUMINIO POTE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            9 =>
            array (
                'id' => 10,
                'code' => 'P010',
                'name' => 'ALUMINIO PERFIL LIMPIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            10 =>
            array (
                'id' => 11,
                'code' => 'P011',
                'name' => 'ALUMINIO OLLA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            11 =>
            array (
                'id' => 12,
                'code' => 'P012',
                'name' => 'ALUMINIO REVUELTO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            12 =>
            array (
                'id' => 13,
                'code' => 'P013',
                'name' => 'ALUMINIO CONTAMINADO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            13 =>
            array (
                'id' => 14,
                'code' => 'P014',
                'name' => 'ALUMINIO PERSIANA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            14 =>
            array (
                'id' => 15,
                'code' => 'P015',
                'name' => 'ALUMINIO PERFIL LIMPIEZA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            15 =>
            array (
                'id' => 16,
                'code' => 'P016',
                'name' => 'GUAYA DE ALUMINIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            16 =>
            array (
                'id' => 17,
                'code' => 'P017',
                'name' => 'LITOGRAFIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            17 =>
            array (
                'id' => 18,
                'code' => 'P018',
                'name' => 'SALCHICHA LIMPIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 21,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            18 =>
            array (
                'id' => 19,
                'code' => 'P019',
                'name' => 'SALCHUCHA SUCIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 21,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            19 =>
            array (
                'id' => 20,
                'code' => 'P020',
                'name' => 'PLOMO LIMPIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 18,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            20 =>
            array (
                'id' => 21,
                'code' => 'P021',
                'name' => 'PLOMO BALACIN',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 18,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            21 =>
            array (
                'id' => 22,
                'code' => 'P022',
                'name' => 'SCRAT',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 18,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            22 =>
            array (
                'id' => 23,
                'code' => 'P023',
                'name' => 'CANASTA LLENA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 4,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            23 =>
            array (
                'id' => 24,
                'code' => 'P024',
                'name' => 'CANASTA VACIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 4,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            24 =>
            array (
                'id' => 25,
                'code' => 'P025',
                'name' => 'CANASTA NEGRA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 4,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            25 =>
            array (
                'id' => 26,
                'code' => 'P026',
                'name' => 'ARCHIVO LIMPIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 6,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            26 =>
            array (
                'id' => 27,
                'code' => 'P027',
                'name' => 'ARCHIVO DE SELECCION',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 6,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            27 =>
            array (
                'id' => 28,
                'code' => 'P028',
                'name' => 'PLEGA-CARTON',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 7,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            28 =>
            array (
                'id' => 29,
                'code' => 'P029',
                'name' => 'VIRUTA DE BRONCE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            29 =>
            array (
                'id' => 30,
                'code' => 'P030',
                'name' => 'VIRUTA DE HIERRO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            30 =>
            array (
                'id' => 31,
                'code' => 'P031',
                'name' => 'VIRUTA DE ALUMINIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            31 =>
            array (
                'id' => 32,
                'code' => 'P032',
                'name' => 'VIRUTA DE ACERO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            32 =>
            array (
                'id' => 33,
                'code' => 'P033',
                'name' => 'BAT N°40/36',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            33 =>
            array (
                'id' => 34,
                'code' => 'P034',
                'name' => 'BAT N°42',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            34 =>
            array (
                'id' => 35,
                'code' => 'P035',
                'name' => 'BAT N°48',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            35 =>
            array (
                'id' => 36,
                'code' => 'P036',
                'name' => 'BAT N°27',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            36 =>
            array (
                'id' => 37,
                'code' => 'P037',
                'name' => 'BAT N°30H',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            37 =>
            array (
                'id' => 38,
                'code' => 'P038',
                'name' => 'BAT N°4D',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            38 =>
            array (
                'id' => 39,
                'code' => 'P039',
                'name' => 'BAT N°8D',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            39 =>
            array (
                'id' => 40,
                'code' => 'P040',
                'name' => 'BAT MOTO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            40 =>
            array (
                'id' => 41,
                'code' => 'P041',
                'name' => 'BAT ESTACIONARIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            41 =>
            array (
                'id' => 42,
                'code' => 'P042',
                'name' => 'PASTA GRUESA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            42 =>
            array (
                'id' => 43,
                'code' => 'P043',
                'name' => 'PASTA SOPLADA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            43 =>
            array (
                'id' => 44,
                'code' => 'P044',
                'name' => 'PASTA REVUELTA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            44 =>
            array (
                'id' => 45,
                'code' => 'P045',
                'name' => 'PASTA NEGRA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            45 =>
            array (
                'id' => 46,
                'code' => 'P046',
                'name' => 'PASTA ACRILICA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            46 =>
            array (
                'id' => 47,
                'code' => 'P047',
                'name' => 'PET TRASPARENTE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            47 =>
            array (
                'id' => 48,
                'code' => 'P048',
                'name' => 'PET VERDE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            48 =>
            array (
                'id' => 49,
                'code' => 'P049',
                'name' => 'COLOR AMBAR PONY',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            49 =>
            array (
                'id' => 50,
                'code' => 'P050',
                'name' => 'PET DE ACEITE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            50 =>
            array (
                'id' => 51,
                'code' => 'P051',
                'name' => 'PVC',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            51 =>
            array (
                'id' => 52,
                'code' => 'P052',
                'name' => 'MANGUERA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 24,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            52 =>
            array (
                'id' => 53,
                'code' => 'P053',
                'name' => 'ENVASE-VIDRIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 8,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            53 =>
            array (
                'id' => 54,
                'code' => 'P054',
                'name' => 'PERIODICO LIMPIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 9,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            54 =>
            array (
                'id' => 55,
                'code' => 'P055',
                'name' => 'PERIODICO ARRUGADO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 9,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            55 =>
            array (
                'id' => 56,
                'code' => 'P056',
                'name' => 'ACERO LIMPIO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 17,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            56 =>
            array (
                'id' => 57,
                'code' => 'P057',
                'name' => 'ACERO CONTAMINADO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 17,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            57 =>
            array (
                'id' => 58,
                'code' => 'P058',
                'name' => 'ENTEROS',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 26,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            58 =>
            array (
                'id' => 59,
                'code' => 'P059',
                'name' => 'TECLAS',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 26,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            59 =>
            array (
                'id' => 60,
                'code' => 'P060',
                'name' => 'RIN DE CARRO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 29,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            60 =>
            array (
                'id' => 61,
                'code' => 'P061',
                'name' => 'RIN DE BICICLETA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 29,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            61 =>
            array (
                'id' => 62,
                'code' => 'P062',
                'name' => 'UNIDAD PIPO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 30,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            62 =>
            array (
                'id' => 63,
                'code' => 'P063',
                'name' => 'UNIDAD NORMAL',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 30,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            63 =>
            array (
                'id' => 64,
                'code' => 'P064',
                'name' => 'UNIDAD GRANDE',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 30,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            64 =>
            array (
                'id' => 65,
                'code' => 'P065',
                'name' => 'VARILLA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            65 =>
            array (
                'id' => 66,
                'code' => 'P066',
                'name' => 'ANGULO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            66 =>
            array (
                'id' => 67,
                'code' => 'P067',
                'name' => 'TUBO',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            67 =>
            array (
                'id' => 68,
                'code' => 'P068',
                'name' => 'PLATINA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            68 =>
            array (
                'id' => 69,
                'code' => 'P069',
                'name' => 'CHATARRA MIXTA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 19,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            69 =>
            array (
                'id' => 70,
                'code' => 'P070',
                'name' => 'CHATARRA ESPECIAL',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 19,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
            70 =>
            array (
                'id' => 71,
                'code' => 'R001',
                'name' => 'RADIOGRAFIA',
                'price' => '0.00',
                'sale_price' => '0.00',
                'commission' => '0.00',
                'stock' => '0.00',
                'stock_min' => '1.00',
                'type_product' => 'product',
                'status' => 'active',
                'category_id' => 32,
                'measure_unit_id' => 767,
                'created_at' => '2024-01-14 12:00:00',
                'updated_at' => '2024-01-14 12:00:00'
            ),
        ));
    }
}
