<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->delete();

        DB::table('products')->insert(array (
            0 =>
            array (
                'id' => 1,
                'code' => 'P001',
                'name' => 'COBRE 1B',
                'price' => '26857.65',
                'sale_price' => '34914.95',
                'stock' => '13.70',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            1 =>
            array (
                'id' => 2,
                'code' => 'P002',
                'name' => 'COBRE MIXTO',
                'price' => '27000.00',
                'sale_price' => '35100.00',
                'stock' => '0.70',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            2 =>
            array (
                'id' => 3,
                'code' => 'P003',
                'name' => 'CABLE DE COBRE',
                'price' => '2000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            3 =>
            array (
                'id' => 4,
                'code' => 'P004',
                'name' => 'RADIADOR DE COBRE',
                'price' => '15500.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 12,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            4 =>
            array (
                'id' => 5,
                'code' => 'P005',
                'name' => 'RADIADOR MIXTO',
                'price' => '12000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 12,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            5 =>
            array (
                'id' => 6,
                'code' => 'P006',
                'name' => 'RADIADOR ALUMINIO',
                'price' => '4691.80',
                'sale_price' => '6099.34',
                'stock' => '24.40',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 12,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            6 =>
            array (
                'id' => 7,
                'code' => 'P007',
                'name' => 'ALUMINIO GRUESO',
                'price' => '5969.56',
                'sale_price' => '7760.43',
                'stock' => '335.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            7 =>
            array (
                'id' => 8,
                'code' => 'P008',
                'name' => 'ALUMINIO BLANDO',
                'price' => '5751.35',
                'sale_price' => '7476.76',
                'stock' => '368.40',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            8 =>
            array (
                'id' => 9,
                'code' => 'P009',
                'name' => 'ALUMINIO POTE',
                'price' => '4998.37',
                'sale_price' => '6497.88',
                'stock' => '307.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            9 =>
            array (
                'id' => 10,
                'code' => 'P010',
                'name' => 'ALUMINIO PERFIL LIMPIO',
                'price' => '7457.69',
                'sale_price' => '9695.00',
                'stock' => '386.40',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            10 =>
            array (
                'id' => 11,
                'code' => 'P011',
                'name' => 'ALUMINIO OLLA',
                'price' => '6200.00',
                'sale_price' => '8060.00',
                'stock' => '50.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            11 =>
            array (
                'id' => 12,
                'code' => 'P012',
                'name' => 'ALUMINIO REVUELTO',
                'price' => '4905.55',
                'sale_price' => '6377.22',
                'stock' => '3.60',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            12 =>
            array (
                'id' => 13,
                'code' => 'P013',
                'name' => 'ALUMINIO CONTAMINADO',
                'price' => '2600.00',
                'sale_price' => '3380.00',
                'stock' => '9.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            13 =>
            array (
                'id' => 14,
                'code' => 'P014',
                'name' => 'ALUMINIO PERSIANA',
                'price' => '900.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            14 =>
            array (
                'id' => 15,
                'code' => 'P015',
                'name' => 'ALUMINIO PERFIL LIMPIEZA',
                'price' => '5000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            15 =>
            array (
                'id' => 16,
                'code' => 'P016',
                'name' => 'GUAYA DE ALUMINIO',
                'price' => '8500.00',
                'sale_price' => '11050.00',
                'stock' => '250.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            16 =>
            array (
                'id' => 17,
                'code' => 'P017',
                'name' => 'LITOGRAFIA',
                'price' => '5500.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 10,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            17 =>
            array (
                'id' => 18,
                'code' => 'P018',
                'name' => 'SALCHICHA LIMPIA',
                'price' => '3500.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 21,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            18 =>
            array (
                'id' => 19,
                'code' => 'P019',
                'name' => 'SALCHUCHA SUCIA',
                'price' => '1800.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 21,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            19 =>
            array (
                'id' => 20,
                'code' => 'P020',
                'name' => 'PLOMO LIMPIO',
                'price' => '5200.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            20 =>
            array (
                'id' => 21,
                'code' => 'P021',
                'name' => 'PLOMO BALACIN',
                'price' => '4000.00',
                'sale_price' => '5200.00',
                'stock' => '0.20',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            21 =>
            array (
                'id' => 22,
                'code' => 'P022',
                'name' => 'SCRAT',
                'price' => '2000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 18,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            22 =>
            array (
                'id' => 23,
                'code' => 'P023',
                'name' => 'CANASTA LLENA',
                'price' => '5000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            23 =>
            array (
                'id' => 24,
                'code' => 'P024',
                'name' => 'CANASTA VACIA',
                'price' => '3562.50',
                'sale_price' => '4631.25',
                'stock' => '4.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            24 =>
            array (
                'id' => 25,
                'code' => 'P025',
                'name' => 'CANASTA NEGRA',
                'price' => '2000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 4,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            25 =>
            array (
                'id' => 26,
                'code' => 'P026',
                'name' => 'ARCHIVO LIMPIO',
                'price' => '829.81',
                'sale_price' => '1078.75',
                'stock' => '75.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 6,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            26 =>
            array (
                'id' => 27,
                'code' => 'P027',
                'name' => 'ARCHIVO DE SELECCION',
                'price' => '850.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 6,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            27 =>
            array (
                'id' => 28,
                'code' => 'P028',
                'name' => 'carton',
                'price' => '449.91',
                'sale_price' => '584.88',
                'stock' => '321.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 7,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            28 =>
            array (
                'id' => 29,
                'code' => 'P029',
                'name' => 'VIRUTA DE BRONCE',
                'price' => '10500.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            29 =>
            array (
                'id' => 30,
                'code' => 'P030',
                'name' => 'VIRUTA DE HIERRO',
                'price' => '250.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            30 =>
            array (
                'id' => 31,
                'code' => 'P031',
                'name' => 'VIRUTA DE ALUMINIO',
                'price' => '800.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            31 =>
            array (
                'id' => 32,
                'code' => 'P032',
                'name' => 'VIRUTA DE ACERO',
                'price' => '2000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 14,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            32 =>
            array (
                'id' => 33,
                'code' => 'P033',
                'name' => 'BAT N°40/36',
                'price' => '25000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            33 =>
            array (
                'id' => 34,
                'code' => 'P034',
                'name' => 'BAT N°42',
                'price' => '30300.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            34 =>
            array (
                'id' => 35,
                'code' => 'P035',
                'name' => 'BAT N°48',
                'price' => '37000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            35 =>
            array (
                'id' => 36,
                'code' => 'P036',
                'name' => 'BAT N°27',
                'price' => '44000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            36 =>
            array (
                'id' => 37,
                'code' => 'P037',
                'name' => 'BAT N°30H',
                'price' => '58500.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            37 =>
            array (
                'id' => 38,
                'code' => 'P038',
                'name' => 'BAT N°4D',
                'price' => '85000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            38 =>
            array (
                'id' => 39,
                'code' => 'P039',
                'name' => 'BAT N°8D',
                'price' => '110000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            39 =>
            array (
                'id' => 40,
                'code' => 'P040',
                'name' => 'BAT MOTO',
                'price' => '3000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            40 =>
            array (
                'id' => 41,
                'code' => 'P041',
                'name' => 'BAT ESTACIONARIA',
                'price' => '2500.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 15,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            41 =>
            array (
                'id' => 42,
                'code' => 'P042',
                'name' => 'PASTA GRUESA',
                'price' => '1004.64',
                'sale_price' => '1306.03',
                'stock' => '48.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            42 =>
            array (
                'id' => 43,
                'code' => 'P043',
                'name' => 'PASTA SOPLADA',
                'price' => '800.00',
                'sale_price' => '1040.00',
                'stock' => '65.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            43 =>
            array (
                'id' => 44,
                'code' => 'P044',
                'name' => 'PASTA REVUELTA',
                'price' => '745.21',
                'sale_price' => '968.77',
                'stock' => '73.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            44 =>
            array (
                'id' => 45,
                'code' => 'P045',
                'name' => 'PASTA NEGRA',
                'price' => '500.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            45 =>
            array (
                'id' => 46,
                'code' => 'P046',
                'name' => 'PASTA ACRILICA',
                'price' => '1000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            46 =>
            array (
                'id' => 47,
                'code' => 'P047',
                'name' => 'PET TRASPARENTE',
                'price' => '1786.65',
                'sale_price' => '2322.64',
                'stock' => '183.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            47 =>
            array (
                'id' => 48,
                'code' => 'P048',
                'name' => 'PET VERDE',
                'price' => '317.86',
                'sale_price' => '413.21',
                'stock' => '28.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            48 =>
            array (
                'id' => 49,
                'code' => 'P049',
                'name' => 'COLOR AMBAR PONY',
                'price' => '204.39',
                'sale_price' => '265.70',
                'stock' => '28.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            49 =>
            array (
                'id' => 50,
                'code' => 'P050',
                'name' => 'PET DE ACEITE',
                'price' => '200.00',
                'sale_price' => '260.00',
                'stock' => '4.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            50 =>
            array (
                'id' => 51,
                'code' => 'P051',
                'name' => 'PVC',
                'price' => '400.00',
                'sale_price' => '520.00',
                'stock' => '39.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 23,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            51 =>
            array (
                'id' => 52,
                'code' => 'P052',
                'name' => 'MANGUERA',
                'price' => '600.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 24,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            52 =>
            array (
                'id' => 53,
                'code' => 'P053',
                'name' => 'ENVASE-VIDRIO',
                'price' => '54.89',
                'sale_price' => '71.35',
                'stock' => '214.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 8,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            53 =>
            array (
                'id' => 54,
                'code' => 'P054',
                'name' => 'PERIODICO LIMPIO',
                'price' => '461.29',
                'sale_price' => '599.68',
                'stock' => '15.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 9,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            54 =>
            array (
                'id' => 55,
                'code' => 'P055',
                'name' => 'PERIODICO ARRUGADO',
                'price' => '300.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 9,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            55 =>
            array (
                'id' => 56,
                'code' => 'P056',
                'name' => 'ACERO LIMPIO',
                'price' => '3433.33',
                'sale_price' => '4463.33',
                'stock' => '21.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 17,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            56 =>
            array (
                'id' => 57,
                'code' => 'P057',
                'name' => 'ACERO CONTAMINADO',
                'price' => '2000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 17,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            57 =>
            array (
                'id' => 58,
                'code' => 'P058',
                'name' => 'ENTEROS',
                'price' => '1000.00',
                'sale_price' => '1300.00',
                'stock' => '1.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 26,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            58 =>
            array (
                'id' => 59,
                'code' => 'P059',
                'name' => 'TECLAS',
                'price' => '2000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 26,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            59 =>
            array (
                'id' => 60,
                'code' => 'P060',
                'name' => 'RIN DE CARRO',
                'price' => '6200.00',
                'sale_price' => '8060.00',
                'stock' => '74.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 29,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            60 =>
            array (
                'id' => 61,
                'code' => 'P061',
                'name' => 'RIN DE BICICLETA',
                'price' => '6200.00',
                'sale_price' => '8060.00',
                'stock' => '8.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 29,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            61 =>
            array (
                'id' => 62,
                'code' => 'P062',
                'name' => 'UNIDAD PIPO',
                'price' => '9000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 30,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            62 =>
            array (
                'id' => 63,
                'code' => 'P063',
                'name' => 'UNIDAD NORMAL',
                'price' => '12000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 30,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            63 =>
            array (
                'id' => 64,
                'code' => 'P064',
                'name' => 'UNIDAD GRANDE',
                'price' => '22000.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 30,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            64 =>
            array (
                'id' => 65,
                'code' => 'P065',
                'name' => 'VARILLA',
                'price' => '1500.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            65 =>
            array (
                'id' => 66,
                'code' => 'P066',
                'name' => 'ANGULO',
                'price' => '1600.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            66 =>
            array (
                'id' => 67,
                'code' => 'P067',
                'name' => 'TUBO',
                'price' => '1600.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            67 =>
            array (
                'id' => 68,
                'code' => 'P068',
                'name' => 'PLATINA',
                'price' => '4200.00',
                'sale_price' => '5460.00',
                'stock' => '2.10',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 31,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            68 =>
            array (
                'id' => 69,
                'code' => 'P069',
                'name' => 'CHATARRA MIXTA',
                'price' => '942.12',
                'sale_price' => '1224.75',
                'stock' => '899.40',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 19,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            69 =>
            array (
                'id' => 70,
                'code' => 'P070',
                'name' => 'CHATARRA ESPECIAL',
                'price' => '1300.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 19,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            70 =>
            array (
                'id' => 71,
                'code' => 'P071',
                'name' => 'RADIOGRAFIA',
                'price' => '2500.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 32,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            71 =>
            array (
                'id' => 72,
                'code' => 'P072',
                'name' => 'BRONCE CONTAMINADO',
                'price' => '12500.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 11,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            72 =>
            array (
                'id' => 73,
                'code' => 'P073',
                'name' => 'BRONCE LIMPIO',
                'price' => '18452.38',
                'sale_price' => '18452.38',
                'stock' => '2.10',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 33,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            73 =>
            array (
                'id' => 74,
                'code' => 'P074',
                'name' => 'PLASTICO',
                'price' => '676.92',
                'sale_price' => '879.99',
                'stock' => '202.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 5,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            74 =>
            array (
                'id' => 75,
                'code' => 'P075',
                'name' => 'CD',
                'price' => '400.00',
                'sale_price' => '520.00',
                'stock' => '1.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 32,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            75 =>
            array (
                'id' => 76,
                'code' => 'P076',
                'name' => 'CD',
                'price' => '400.00',
                'sale_price' => '0.00',
                'stock' => '0.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 32,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            76 =>
            array (
                'id' => 77,
                'code' => 'P077',
                'name' => 'LATA',
                'price' => '4169.37',
                'sale_price' => '5420.18',
                'stock' => '76.40',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 32,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            77 =>
            array (
                'id' => 78,
                'code' => 'P078',
                'name' => 'PANAN',
                'price' => '1000.00',
                'sale_price' => '1300.00',
                'stock' => '10.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 32,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            78 =>
            array (
                'id' => 79,
                'code' => 'P079',
                'name' => 'TAPA',
                'price' => '530.77',
                'sale_price' => '690.00',
                'stock' => '6.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 32,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            79 =>
            array (
                'id' => 80,
                'code' => 'P080',
                'name' => 'TARJETA',
                'price' => '5000.00',
                'sale_price' => '6500.00',
                'stock' => '0.40',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 32,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),
            80 =>
            array (
                'id' => 81,
                'code' => 'P081',
                'name' => 'PLEGA',
                'price' => '200.00',
                'sale_price' => '260.00',
                'stock' => '78.50',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 7,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            81 =>
            array (
                'id' => 82,
                'code' => 'P082',
                'name' => 'HIERRO GRIS',
                'price' => '1300.00',
                'sale_price' => '1690.00',
                'stock' => '6.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 2,
                'measure_unit_id' => 767,
                'created_at' => null,
                'updated_at' => null
            ),
            82 =>
            array (
                'id' => 83,
                'code' => 'P084',
                'name' => 'DESODORANTE',
                'price' => '2310.00',
                'sale_price' => '3003.00',
                'stock' => '2.00',
                'commission' => 0,
                'stock_min' => 0,
                'type_product' => 'product',
                'status' => 'active',
                'imageName' => null,
                'image' => null,
                'category_id' => 32,
                'measure_unit_id' => 70,
                'created_at' => null,
                'updated_at' => null
            ),

        ));
    }
}
