<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvidersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('providers')->delete();

        DB::table('providers')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'JESUS MARIA GUEVARA',
                'identification' => '91226775',
                'dv' => 1,
                'address' => 'calle 5 16-56',
                'phone' => '11111',
                'email' => 'Jess@gmail.com',
                'merchant_registration' => '000000-0',
                'contact' => '3102642597',
                'phone_contact' => '25461878',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2736,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'julio Díaz cristancho',
                'identification' => '55612432',
                'dv' => 5,
                'address' => 'calle 6 -22-11',
                'phone' => '6548765',
                'email' => 'julio@gmail.com',
                'merchant_registration' => '000000-0',
                'contact' => 'julio cristancho',
                'phone_contact' => '56598263',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 393,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Orlando López',
                'identification' => '16760399',
                'dv' => 1,
                'address' => 'calle 5 - 19',
                'phone' => '564989456',
                'email' => 'orlando@gmail.com',
                'merchant_registration' => '000000-0',
                'contact' => 'orlando',
                'phone_contact' => '54951524',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Wilmer moreno',
                'identification' => '22318281',
                'dv' => 1,
                'address' => 'calle 27 -25',
                'phone' => '316555',
                'email' => 'wilmer@gmail.com',
                'merchant_registration' => '000000-0',
                'contact' => '1248978541',
                'phone_contact' => '21412323156',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Henry Gómez',
                'identification' => '1098638702',
                'dv' => 9,
                'address' => 'carrera 7-25',
                'phone' => '15648974561',
                'email' => 'henry@gmail.com',
                'merchant_registration' => '000000-0',
                'contact' => 'HENRY',
                'phone_contact' => '3126489456',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'LUIS ANTONIO SIZA',
                'identification' => '91235440',
                'dv' => 8,
                'address' => 'CALLE8-85',
                'phone' => '316555',
                'email' => 'SIZA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => 'LUIS',
                'phone_contact' => '3,12542E+11',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2737,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'ADRIAN QUINTANA',
                'identification' => '31530294',
                'dv' => 5,
                'address' => 'carrera25-15',
                'phone' => '31548942315',
                'email' => 'adrian@gmail.com',
                'merchant_registration' => '000000-0',
                'contact' => 'adrian',
                'phone_contact' => '3215484885',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2734,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Carlos Lopera',
                'identification' => '91475981',
                'dv' => 1,
                'address' => 'carrera 15-54',
                'phone' => '3254681585',
                'email' => 'carlos@gmail.com',
                'merchant_registration' => '000000-0',
                'contact' => 'carlos',
                'phone_contact' => '564564541',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2736,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'yorguin lozano',
                'identification' => '1192773065',
                'dv' => 3,
                'address' => 'carrera 58-45',
                'phone' => '31564894',
                'email' => 'lozano@gmail.com',
                'merchant_registration' => '000000-0',
                'contact' => 'yorguin',
                'phone_contact' => '264894561',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2736,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Gabriel fuentes',
                'identification' => '1098629839',
                'dv' => 0,
                'address' => 'carrera 25-65',
                'phone' => '23154451',
                'email' => 'fuentes@gmail.com',
                'merchant_registration' => '000000-0',
                'contact' => 'gabriel',
                'phone_contact' => '24894561',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Andrés Toloza',
                'identification' => '1096065072',
                'dv' => 1,
                'address' => 'carrera 5 -65',
                'phone' => '1415645612',
                'email' => 'andres@gmail.com',
                'merchant_registration' => '000000-0',
                'contact' => 'toloza',
                'phone_contact' => '3241548949',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2736,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'JEISON CASTILLO',
                'identification' => '24548380',
                'dv' => 4,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@HOTMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'JORGE MOYA',
                'identification' => '1098633540',
                'dv' => 1,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@HOTMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'SANTIAGO OSPINA',
                'identification' => '1118289346',
                'dv' => 3,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@HOTMAIL.VOM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'JORGE ORTIZ',
                'identification' => '12345678',
                'dv' => 8,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'JHON ROMAN',
                'identification' => '123456789',
                'dv' => 6,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@HOTMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'LUIS JOSE DUARTE',
                'identification' => '1234567896',
                'dv' => 6,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'RAFAEL RAMIREZ',
                'identification' => '1234567892',
                'dv' => 7,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'GIOVANNY MALDONADO',
                'identification' => '12345678987',
                'dv' => 0,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'JORGE GARCIA',
                'identification' => '56987265',
                'dv' => 4,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'HERNAN GUTIERREZ',
                'identification' => '1100888005',
                'dv' => 1,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'MATEO TORREZ',
                'identification' => '1097096067',
                'dv' => 9,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'OVIEDO GROZ',
                'identification' => '5722566',
                'dv' => 3,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'ERIKA',
                'identification' => '37854693',
                'dv' => 3,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            24 =>
            array (
                'id' => 25,
                'name' => 'MELANY',
                'identification' => '15698354',
                'dv' => 2,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            25 =>
            array (
                'id' => 26,
                'name' => 'MANEL',
                'identification' => '98765432',
                'dv' => 8,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            26 =>
            array (
                'id' => 27,
                'name' => 'RENE ESPINOZA',
                'identification' => '79589074',
                'dv' => 0,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            27 =>
            array (
                'id' => 28,
                'name' => 'MARLON GARCIA',
                'identification' => '10396941',
                'dv' => 1,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            28 =>
            array (
                'id' => 29,
                'name' => 'SEBASTIAN OSPINA',
                'identification' => '1095956520',
                'dv' => 8,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            29 =>
            array (
                'id' => 30,
                'name' => 'ALEX PEREZ',
                'identification' => '1090503664',
                'dv' => 8,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            30 =>
            array (
                'id' => 31,
                'name' => 'SANTIAGO OSPINA',
                'identification' => '1118289396',
                'dv' => 1,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            31 =>
            array (
                'id' => 32,
                'name' => 'GRAN MUEBLES',
                'identification' => '56145651',
                'dv' => 1,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            32 =>
            array (
                'id' => 33,
                'name' => 'OVIEDO DIAZ',
                'identification' => '65984235',
                'dv' => 2,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLIACA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            33 =>
            array (
                'id' => 34,
                'name' => 'CHAUSTRE',
                'identification' => '1234555697',
                'dv' => 5,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            34 =>
            array (
                'id' => 35,
                'name' => 'GREGORIO GOMEZ',
                'identification' => '63524569',
                'dv' => 7,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            35 =>
            array (
                'id' => 36,
                'name' => 'LUIS ARIEL RUBIO',
                'identification' => '5727197',
                'dv' => 1,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            36 =>
            array (
                'id' => 37,
                'name' => 'MERECEDES ANGARITA',
                'identification' => '63501770',
                'dv' => 2,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            37 =>
            array (
                'id' => 38,
                'name' => 'PEDRO',
                'identification' => '261565261',
                'dv' => 8,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            38 =>
            array (
                'id' => 39,
                'name' => 'WILSON HERNANDEZ',
                'identification' => '5265985',
                'dv' => 0,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 2,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            39 =>
            array (
                'id' => 40,
                'name' => 'ALIX JAIMES',
                'identification' => '63316925',
                'dv' => 4,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            40 =>
            array (
                'id' => 41,
                'name' => 'MARTHA SAAVEDRA',
                'identification' => '37941175',
                'dv' => 2,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            41 =>
            array (
                'id' => 42,
                'name' => 'LUIS E. RODRIGUEZ',
                'identification' => '13920522',
                'dv' => 8,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            42 =>
            array (
                'id' => 43,
                'name' => 'LUIS DURAN',
                'identification' => '91464839',
                'dv' => 4,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            43 =>
            array (
                'id' => 44,
                'name' => 'GUSTAVO RAMIREZ',
                'identification' => '13818197',
                'dv' => 1,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            44 =>
            array (
                'id' => 45,
                'name' => 'CHISPA',
                'identification' => '65235986',
                'dv' => 2,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            45 =>
            array (
                'id' => 46,
                'name' => 'JOEL',
                'identification' => '98756245',
                'dv' => 9,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            46 =>
            array (
                'id' => 47,
                'name' => 'MANUEL',
                'identification' => '96523258',
                'dv' => 7,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            47 =>
            array (
                'id' => 48,
                'name' => 'GUSTAVO -FORTUNATO',
                'identification' => '914562435',
                'dv' => 7,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            48 =>
            array (
                'id' => 49,
                'name' => 'CRISTIAN',
                'identification' => '91584763',
                'dv' => 8,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@HOTMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            49 =>
            array (
                'id' => 50,
                'name' => 'PAOLA VELASQUEZ',
                'identification' => '1098612022',
                'dv' => 6,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            50 =>
            array (
                'id' => 51,
                'name' => 'BRAYAN S',
                'identification' => '1097063544',
                'dv' => 9,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            51 =>
            array (
                'id' => 52,
                'name' => 'FERNANDO (NANDO)',
                'identification' => '58621458',
                'dv' => 0,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 2,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            52 =>
            array (
                'id' => 53,
                'name' => 'JHON HERRERA',
                'identification' => '91534156',
                'dv' => 3,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            53 =>
            array (
                'id' => 54,
                'name' => 'ALEJANDRO PINZON',
                'identification' => '3812708',
                'dv' => 1,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            54 =>
            array (
                'id' => 55,
                'name' => 'KUKI',
                'identification' => '63259336',
                'dv' => 1,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            55 =>
            array (
                'id' => 56,
                'name' => 'JONATHAN COLMENARES',
                'identification' => '109818290',
                'dv' => 7,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),
            56 =>
            array (
                'id' => 57,
                'name' => 'JORGE MOLINA',
                'identification' => '91206442',
                'dv' => 9,
                'address' => 'BUCARAMANGA',
                'phone' => '316555',
                'email' => 'NOAPLICA@GMAIL.COM',
                'merchant_registration' => '000000-0',
                'contact' => '\N',
                'phone_contact' => '\N',
                'status' => 'active',
                'department_id' => 21,
                'municipality_id' => 846,
                'postal_code_id' => 2733,
                'identification_type_id' => 3,
                'liability_id' => 117,
                'organization_id' => 2,
                'regime_id' => 2,
                'created_at' => '2024-07-25 12:00:00',
                'updated_at' => '2024-07-25 12:00:00'
            ),

        ));
    }
}
